### ISSUE TITLE
The focus change not following the model change

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/templating#104]
added this to the welcome.html view, of the just cloned skeleton-navigation:
```html   
    <input id="id1" focus.bind="fid1">
    <input id="id2" focus.bind="fid2">
```
and this to welcome.js model:
```javascript
  constructor () {
    this.intervalID = setInterval(this.reFocus, 2000);
    this.fid2 = true;
    this.fid1 = false;
  }

  reFocus() {
    if (this.fid1) {
      this.fid2 = true;
      this.fid1 = false;
    } else {
      this.fid1 = true;
      this.fid2 = false;
    }
    console.log(this.fid1, this.fid2);
  }
```
After opening the view, the initial focus is set correctly, on 2nd input field. The console output shows this.fid1 and fid2 alternating **true** and **false** but the focus change in web browser is not happening.
Should this example work ?

**Comment by ZapMyR** [comment]
Actually this is not a problem of Aurelia. When you use <code>setInterval</code> the <code>this</code> you are using to point to <code>reFocus</code> is misleading. It's used to point at what function to call, but it doesn't ensure the <code>this</code>-scope for when the function actually gets called after the interval has elapsed.

To get your example working you can just wrap <code>reFocus</code> inside a self-calling function, because the call of a function decides what your <code>this</code>-scope is.

Here's an example of how it should work for you:

    this.intervalID = setInterval(function(self) {
      return function() {
        self.reFocus();
      }
    }(this), 2000);
