### ISSUE TITLE
Custom element marked @noView should not discard child elements of the custom element.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#127]
If I have the following HTML construct:

`<outer-custom-element>
   <some-custom-element></some-custom-element>
</outer-custom-element>`

And if the ViewModel class for `<outer-custom-element>` is marked with the @noView decorator, then I believe that the inner elements should be retained within the DOM. At present it appears that the inner elements of `<outer-custom-element>` get cleared during the templating or binding process.

The workaround appears to be to put a `<content select="*">` element into the HTML and remove the @noView attribute, but it seems counterproductive to do this (another file to maintain, etc).

(The use of a separate decorator to deal with this situation might be a reasonable solution).

**Comment by kevmeister68** [comment]
Correction to above - the HTML disappeared:

<outer-custom-element>
   <inner-custom-element></inner-custom-element>
</outer-custom-element>

**Comment by EisenbergEffect** [comment]
Can you give me steps to reproduce? It sounds like a bug.

**Comment by shanonvl** [comment]
>(The use of a separate decorator to deal with this situation might be a reasonable solution).

To that end, would @skipContentProcessing on the OuterCustomElement view model work here?   Perhaps @noView should also skip content processing, however I believe that using the additional decorator may also work.

**Comment by kevmeister68** [comment]
> would @skipContentProcessing on the OuterCustomElement view model work here?

I'm not sure it would in my situation as I still want to embed custom elements inside the OuterCustomElement and would still expect the templating engine to instantiate view-models etc for those inner custom elements.

**Comment by kevmeister68** [comment]
Rob, I'm a little bit new to the whole github thing, but I have created a gist that you can download. Copy the files into your skeleton-navigation app (src folder), and then launch http://localhost:9000/index.html#test.

https://gist.github.com/kevmeister68/27f0ea35f912b55a83a3

Hope this shows what I mean.

**Comment by EisenbergEffect** [comment]
@kevmeister68 The problem is that if you specify `@noView` then what should be done with the content of the custom element? Without a view and a content projection site, there's literally nowhere to render that content. For this reason, when you specify that you want noView, if you are expexting content, then you usually turn of content processing and do it yourself, or provide a custom content processing function (new in the latest release). But, just to re-iterate, the browser literally doesn't know how to render the custom element's inner content without a reproduction site (<content> tag).

**Comment by kevmeister68** [comment]
Hi Rob,

 

I had to re-read that sentence a couple of times, but it has dawned upon me what you are saying. My understanding of @noView is clearly wrong.

 

You are saying that @noView means there will be no Node in the DOM which acts a “content projection site”.

 

My understanding was that @noView literally meant “there is no HTML file to be loaded” but beyond that the custom-element still existed [somehow] in the DOM (ie. with empty content).

 

In effect I was using @noView to avoid putting an empty <template></template> pair in a HTML file. Perhaps it cannot be strictly empty – perhaps it needs to be <template><div></div></template>? 

 

Is there a better way to describe/define that?

 

When you say at the end of your comment “reproduction site (tag)”, are you simply talking about having a HTML element in the DOM, versus not having one?

 

Thanks

 

Kevin

**Comment by EisenbergEffect** [comment]
Not quite. There will be an element in the DOM. But, if you place content inside that element, it cannot be rendered because the browser does not know "where" to render it. That's what the `<content>` tag does. It tells the browser (and Aurelia when we fallback to our polyfill) where to put the element's content. So, minimally, you would need this: `<template><content></content></template>`.

**Comment by kevmeister68** [comment]
So by any chance is there a decorator that could adorn a class to give me this "empty template" in a similar vein to @noView, but with the inner content semantics that I need, as described above? Or would writing one be easy enough? Seems a shame to specify these virtually-unnecessary .html files (views) for this situation.

**Comment by EisenbergEffect** [comment]
As a matter of fact...

```
@inlineView('<content></content>')
```

That should do it.
