### ISSUE TITLE
[Feature] Containerless composition 

### ISSUE THREAD

**Issue by Craga89** [aurelia/templating#16]
Unlike Durandal 2.x the framework doesn't seem to support Containerless composition, which could be a sticking point for folks utilising that functionality who want to eventually migrate. 

Once I'm more accustomed to Aurelias internals I'll have a crack at implementing it and send a PR your way.

**Comment by EisenbergEffect** [comment]
I think it might not be too much trouble to do this. What it would involve is us adding a method onto the ViewSlot that switches it into anchor mode. The TemplateContrllers use it this way by default and the CustomElement use it to push views internally by default. So, we just need to give the ViewSlot the capability to switch modes...and I think we should have it.

**Comment by csaloio1** [comment]
I think this could be helpful much in the same way angularJS allows a template to "replace" its directive element in the DOM. But I think it may be important for attributes on the customElement to be passed on to the root element in its template. So If I'm a dropdown control customElement consumers should ideally be able to specify the tabindex, classes, and style attribute of their choice and have that pass on to the root element in the viewTemplate which would replace the customElement in the DOM.

**Comment by EisenbergEffect** [comment]
The next release will have support for this. To turn a `compose` or `router-view` into a containerless composition, add the `containerless` attribute to the element. You can also now create custom elements that are containerless, by using the `@containerless` decorator. There is no attribute forwarding. We don't want people to use this very much since it's not aligned with web components. The core capability is primarily to support containerless composition and a few edge cases, possibly SVG composition.
