### ISSUE TITLE
August release: nested <template> are broken in IE

### ISSUE THREAD

**Issue by jods4** [aurelia/templating#169]
In IE, there is a showstopper bug in August release.

Having a view with `<template>` tag inside, even as simple as:
```html
<template>
  <template if="true">
    Yes
  </template>
</template>
```

Results in a Stack overflow in IE 11. My application currently does not work at all in IE 9-10 but right now I can't tell if the issue is linked to this or not.

It works in latest FF and Cr, but both have native support for `<template>`.

I tried to put back the `webcomponentsjs` polyfill that was used in previous release, but it did not make any difference.

This is critical enough that I have to rollback to September release.

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Do either of you have time to look into this?

**Comment by jdanyow** [comment]
1. In both IE11 and Chrome, the Initial call to compile lands [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L73).
In IE11, source is an instanceof HTMLUnknownElement and source.content is an instanceof DocumentFragment.
In Chrome, source is an instanceof HTMLTemplateElement and source.content is instanceof DocumentFragment.

2. Both IE11 and Chrome go [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L127) next.  In IE11, currentChild is an HTMLUnknownElement representing the inner <template>, in Chrome, it's an HTMLTemplateElement.

3. Next both IE11 and Chrome go [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L103)

4. In compileElement both IE11 and Chrome go [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L246)

5. This is where IE11 and Chrome diverge.  In step 4, compile is invoked a second time.  Chrome lands [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L71) because the inner template element has a content property.  In IE11 the inner template element's content property is undefined, causing it to land [here](https://github.com/aurelia/templating/blob/0.15.3/src/view-compiler.js#L75) and get stuck in a loop of `compile`, `compileNode`, `compileElement`, `compile`, `compileNode`, `compileElement`, `compile`, `compileNode`, `compileElement`, `compile`, `compileNode`, `compileElement`, ...

@EisenbergEffect, I'm a little out of my depth here, maybe this tells you something?

**Comment by EisenbergEffect** [comment]
Yes...yes it does. Something is going wrong with template bootstrapping it sounds like. I'll see if I can get an windows instance up and running so I can debug where that is going wrong. But, this definitely helps. It's something we can fix.

**Comment by jdanyow** [comment]
I wonder if the fix for this will also fix https://github.com/aurelia/templating/issues/161

**Comment by EisenbergEffect** [comment]
I strongly suspect it will.

**Comment by npelletm** [comment]
Same issue with aurelia 18 september master github source

**Comment by jods4** [comment]
This needs to be fixed with a high priority. It is blocking any upgrade to August release or later (for me at least).

**Comment by michaelmalonenz** [comment]
Don't know if this information helps (might be obvious to you folk) but the problem goes away if you go back to using Html Template Imports.
```javascript
jspm install aurelia-html-import-template-loader   

.plugin('aurelia-html-import-template-loader')
```

**Comment by EisenbergEffect** [comment]
I think it's an issue with incorrectly bootstrapped nested templates in IE for the text loader. We have a new version coming out this week with a fix for that.

**Comment by michaelmalonenz** [comment]
Fantastic - thanks!

**Comment by EisenbergEffect** [comment]
Fixed in master. Going out in the next release within a day or two.
