### ISSUE TITLE
Attached Behavior properties that are not the "attached behavior's attribute" bound with `.call` are always undefined

### ISSUE THREAD

**Issue by yelvert** [aurelia/templating#19]
Behavior - https://github.com/yelvert/aurelia-interface/blob/ddd7c13be1b32984ba1b7da494cbec6220ddab83/src/ai-tabs.js#L6-L8
Use in HTML - https://github.com/yelvert/aurelia-interface/blob/b89c458bce73967c9fbb6b27f81eb78f5ca7df9e/src/tabs-demo.html#L3
Parent VM - https://github.com/yelvert/aurelia-interface/blob/b89c458bce73967c9fbb6b27f81eb78f5ca7df9e/src/tabs-demo.js#L7-L13

In the attached behavior, `_showTab` and `_hideTab` are always undefined.

Sorry if this is the wrong repo for this issue.

**Comment by EisenbergEffect** [comment]
I think this is something that maybe isn't clear in the documentation but....attached behaviors must has a one-to-one correspondence with attributes in html. You can't actually write what you are trying to write. However, we do support what we call "options" property which function like the native style attribute and allow embedding of multiple properties inside of a single attribute.

You should change your metadata to this:

```javascript
static metadata () {
    return Behavior
      .withOptions().and(x => {
        x.withProperty('activeTabRef', 'tabRefChanged', 'ai-tabs').and( x => x.bindingIsTwoWay());
        x.withProperty('_showTab', 'showTabChanged', 'ai-show-tab');
        x.withProperty('_hideTab', 'hideTabChanged', 'ai-hide-tab');
      });
      .syncChildren('tabLinks', 'tabLinksChanged', '[ai-tab-link]');
  }
```

(Note that you don't need the `noView()` call because attached behaviors don't have views.)

You would then use it like this:

```markup
<div ai-tabs="activeTabRef.bind: selectedTabRef; ai-show-tab.call: showMyTab(tab); ai-hide-tab.call: hideMyTab(tab)">
```

This seems like something that is better suited to being a custom element, BTW.

**Comment by EisenbergEffect** [comment]
Note that when you do this, you can remove the `ai-` prefixes on the inner names since they are now inside the options and there is no confusion regarding naming.

**Comment by yelvert** [comment]
When doing this, I get `undefined is not a function` error, for the `.and( x => x.bindingIsTwoWay())`
