### ISSUE TITLE
router-view content doesn't rebind

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating#210]
This was reported by @jedd-ahyoung on [stackoverflow](http://stackoverflow.com/questions/33674752/custom-element-issue-ref-element-is-null-in-viewmodel/).  I've distilled the repro down as much as I could but haven't been able to figure it out.

When you toggle a div containing a router-view, the router-view's content (the welcome module) becomes unbound and never rebinds.

## Minimal repro:

**app.js**
```js
export class App {
  configureRouter(config) {
    config.map([{ route: '', moduleId: 'welcome' }]);
  }
}
```
**app.html**
```html
<template>
  <button click.delegate="foo = !foo">toggle</button>
  <div if.bind="!foo">
    <router-view></router-view>
  </div>
</template>
```
**welcome.js**
```js
export class Welcome {
  bind(bindingContext, overrideContext) { console.info('WELCOME: BIND'); }
  unbind() { console.info('WELCOME: UNBIND'); }
  attached() { console.info('WELCOME: ATTACHED'); }
  detached() { console.info('WELCOME: DETACHED'); }
}
```
**welcome.html**
```html
<template>hello world</template>
```

## App
![app](http://i.imgur.com/4eS9YyY.png)

## Steps:
**1. Run...**
  ![console](http://i.imgur.com/e02SC5R.png)

**2. Press the toggle button to remove the div containing the router-view...**
  ![console](http://i.imgur.com/6NS0ySf.png)
   so far so good...

**3. Press the toggle button again to re-add the div containing the router-view...**
  ![console](http://i.imgur.com/LwN3hHg.png)
  *the `Welcome.bind` is not called*

**Comment by EisenbergEffect** [comment]
I think it's just a use case that isn't accounted for. For example, the controller/view of the current route isn't stored anywhere. So, when an unbind or bind happens it can't respond appropriately.

But I think there may be a deeper issue. The ViewSlot that the router-view uses is added to the children collection of the owning view...which is why the unbind happens. Maybe the view slot shouldn't be added into that collection. Perhaps the router-view (and compose by extension) should just entirely manage the slot.

Thoughts?

**Comment by jdanyow** [comment]
>The ViewSlot that the router-view uses is added to the children collection of the owning view...which is why the unbind happens.

glad you mentioned that^^^.  It's making sense to me now.

>Perhaps the router-view (and compose by extension) should just entirely manage the slot.

also makes sense to me^^^.  Would this change be a big lift?

**Comment by EisenbergEffect** [comment]
Actually....I'm not sure if we want to make that change because it means that the slot's attached and detached would have to be managed...basically router-view, compose and any other similar element or template controller would need to manage it.

Instead, I think we can solve the problem by just keeping the internal controller around and if present on a bind, manually re-binding it.

**Comment by EisenbergEffect** [comment]
For now, router-views need to be statically defined.
