### ISSUE TITLE
after upgrading to beta viewCompiler compiled fragment's context is null

### ISSUE THREAD

**Issue by devmondo** [aurelia/templating#214]
this used to work before but now the `ctx` is always null thus no binding is working

**compiler class**

```
import {inject, ViewCompiler, ViewResources, Container} from 'aurelia-framework';

@inject(ViewCompiler, ViewResources, Container)
export class ViewFactory {
  constructor(viewCompiler, resources, container) {
    this.viewCompiler = viewCompiler;
    this.resources = resources;
    this.container = container;
  }

  create(html, viewModel) {
    let view = this.viewCompiler.compile(html, this.resources)
      .create(this.container, viewModel);

    return view;
  }
}
```
**usage in viewModel**
```
let view = this.viewFactory.create('<div>${test}</div>', this);
this.element.appendChild(view.fragment);
```
so the viewmodel above have a property called test, but it does not show in html in browser

thx in advanced.

**Comment by EisenbergEffect** [comment]
The API changes. In order for us to make a bunch of improvements, we fully separated the creation of the view from the binding of the view.

As a result, the `create` method does not take a view model. You should first call `create` to get the view, then you would call `bind` on the view, passing your view model.

That said, you aren't quite using the view in a way that is going to guarantee 100% behavior because you are just manually adding the fragment. Instead, create a ViewSlot instance for the element you wan to append to, like this `let slot = new ViewSlot(element, true);`

Then add thew view to the slot `slot.add(view)`; Then call `slot.attached()`.

**Comment by devmondo** [comment]
thx rob :) it works now
