### ISSUE TITLE
Proposal for the improvement of <require> element

### ISSUE THREAD

**Issue by adriatic** [aurelia/templating#223]
Example: Aurelia-KendoUI plugin uses this form:
```html
<require from="kendo-ui/styles/web/css/kendo.materialblack.min.css"></require>
```

If I could change the value of the **`from`** attribute at runtime, that would allow me to change the application's "look and feel" at a click of a say radio-button. Of course, it is developer's responsibility to use this feature in a consistent fashion.

**Comment by EisenbergEffect** [comment]
We aren't going to make this dynamic because `require` in html is designed to work like `import` in JavaScript, in that it is statically analyzable.

For your scenario, a better solution would be to create a custom element, perhaps called `kendo-theme` and give it a theme property. Then it can simply use the Aurelia loader to download the specified theme whenever the property changes and inject it into the head. It can also remove the previous theme, if present. Something like this:

```
import {Loader, bindable} from 'aurelia-framework';

@inject(Loader)
export class KendoTheme {
  @bindable theme;

  constructor(loader) {
    this.loader = loader;
  }

  themeChanged(newValue) {
    this.loader.loadText(newValue).then(text => {
      //remove old style element from head
      //add new style to head, using the text for the css
    });
  }
}
```

This code is not tests, but you should get the general idea. Because you are loading the css as text through the loader, it also means that the kendo css can be bundled, if desired.

The only caveat to this method is that there may be a flash of unstyled content while the theme downloads. We are planning a way to queue up async composition requests in the near future that would hold back rendering until the async work is complete. This could be used to solve that problem, by ensuring that the styles are downloaded before the composition is complete.

**Comment by adriatic** [comment]
Need just a bit more guidance as my use case is:

File **app.html**
```html
<template>
    <require from="bootstrap/css/bootstrap.css"></require>
    <require from="kendo-ui/styles/web/css/kendo.common.min.css"></require>
    <require from="kendo-ui/styles/web/css/kendo.materialblack.min.css"></require>

    <require from="./nav-bar"></require>

  	<nav-bar router.bind="router"></nav-bar>

  	<div class="page-host">
        <router-view></router-view>
	</div>
</template>
```

As the actions take place withing the `<template>` element I do not see how to do the part
```
      //remove old style element from head
      //add new style to head, using the text for the css
```
to achieve the equivalent of replacing the value of the `from` attribute on the third `<require>` element above.

**Comment by EisenbergEffect** [comment]
First, you wouldn't include the third css require at all. If you include that, that tells Aurelia to add it to the head  automatically, which is not what you want.

To implement the body of the method above, you can use our DOM helper.

```
let styleElement = DOM.injectStyles(styleText);
```

That will create a style element with the text you provide, add it to the head of the document and then return the created style element back to you.

**Comment by adriatic** [comment]
Perfect - thank you Rob!
