### ISSUE TITLE
Additional "$parent" required when binding to radio button in template part

### ISSUE THREAD

**Issue by jc1001** [aurelia/templating#242]
Not sure if this is an issue, but the behavior does seem a little strange. I downloaded the ES2016 starter kit and updated the jspm packages to the latest versions.  

Changed the app.js to:
```javascript
export class App {
  message = 'Welcome to Aurelia!';
  colors = ['Red', 'Blue', 'Green'];
  favoriteColor = 'Green';
}
```
Changed app.html to:
```javascript
<template>
  <h1>${message}</h1>
  <label repeat.for="color of colors">
    <input type="radio" name="clrs" value.bind="color" checked.bind="$parent.favoriteColor" />
    ${color}
  </label>
</template>
```
as per the radio button binding example on the cheat sheet.

The correct radio button is checked:
![valid](https://cloud.githubusercontent.com/assets/15125812/12118064/23632bc2-b3cd-11e5-85a6-6e39337e8c9f.PNG)

I then added a new template "mytemplate":
```javascript
<template>
  <div style="background-color:red">
    <template replaceable part="thecontent">
      PUT CONTENT HERE
    </template>        
  </div>
</template>
```
and changed app.html to:
```javascript
<template>
  <require from='./mytemplate.html' as="mytemplate"></require>  
    <mytemplate>
      <template replace-part="thecontent">
        <h1>${message}</h1>
        <label repeat.for="color of colors">
          <input type="radio" name="clrs" value.bind="color" checked.bind="$parent.favoriteColor" />
          ${color}
        </label>
      </template>
    </mytemplate>
</template>
```
When rendering now, the radio button is not checked:
![invalid](https://cloud.githubusercontent.com/assets/15125812/12118307/635c3808-b3ce-11e5-8748-6c2a59d32e34.PNG)

If I change the checked.bind value to "$parent.$parent.favoriteColor", the radio button is checked again:
![validagain](https://cloud.githubusercontent.com/assets/15125812/12118340/995de8a2-b3ce-11e5-8200-100fdfff160b.PNG)

Is this behavior correct?

**Comment by EisenbergEffect** [comment]
That behavior is correct because your template part is binding inside the inner context of the custom element. Basically, a template part binds as if it were written inside the custom element's view. So, it requires additional "hopping" to bind back to the data source you are trying to get to.

That said, try simplifying all of these examples by removing $parent from everthing so that you just have `checked.bind="favoriteColor"` We did some work for the beta to automatically check parent contexts, so using $parent should be rare. Let me know if that works for you.

**Comment by jc1001** [comment]
Removing all the "$parent" identifiers did solve the problem.  Thank you for the quick response.

**Comment by EisenbergEffect** [comment]
Looks like we need to update that cheat sheet :)
