### ISSUE TITLE
Specifying default value for custom element property with changed callback doesn't change value

### ISSUE THREAD

**Issue by SAAirey** [aurelia/templating#25]
I have a custom element defined with a property like so:

```js
  static metadata() {
    return Behavior
      .customElement('my-element')
      .withProperty('myProperty', null, 'myProperty', 'default', 'one-time');
  }
```

And then in my view:

```html
<my-element my-property="not default"></my-element>
```

I want to wait until the element has been attached to the DOM so that I can do some things with it, so I wrote an `attached()` method like so:

```js
attached() {
  console.log(this.myProperty);
}
```

I would expect the value of `this.myProperty` to be `not default` at this stage but it is still `default` so I tried modifying my property definition to this:

```js
.withProperty('myProperty', 'myPropertyChanged, 'myProperty', 'default', 'one-time');
```

And added the handler:

```js
myPropertyChanged(newValue) {
  console.log(`changed`, newValue);
}
```

Except the changed handler is never called.

If I changed my property definition to this (accepting all defaults):

```js
.withProperty('myProperty');
```

Then the value I see for `this.myProperty` in `attached()` is `not default` as expected.

**Comment by SAAirey** [comment]
Something I think would be useful in addition to this would be an event or method that we can hook into after all properties have been bound from the view

**Comment by SAAirey** [comment]
Sorry, wrong button...

**Comment by EisenbergEffect** [comment]
Ok, finally got around to investigating this. Turns out it's not a bug in the framework. There are a couple of errors in the code above. First is that the binding mode isn't a string, it's an integer. This is represented by a variable that is exported from the framework. In the new version, releasing tomorrow, there are some changes around that. So, in the new version you would do this `bindingMode.oneTime`

Also, the attribute specified is not a valid html attribute. When you are explicit about the attribute aurelia does not try to alter it. In this case you specified `myProperty` as the attribute name, rather than `my-property` which is what you actually used.

In the latest version of the codebase, this is how I would define my property (using ES7):

```
import {bindable, bindingMode} from 'aurelia-framework';

export class MyElement {
  @bindable({defaultBindingMode:bindingMode.oneTime}) myProperty = 'default';

  attached() {
    console.log(this.myProperty);
  }
}
```
