### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by DiegoGallegos4** [aurelia/templating#259]
I saw this error on issues a couple of months but I downloaded the skeleton for ES6 today and just found this error on the console. 

Error on console: 
**getAnimatableElement	@	aurelia-templating.js:1100
removeAt	@	aurelia-templating.js:1252
remove	@	aurelia-templating.js:1227
(anonymous function)	@	if.js:34
flushMicroTaskQueue	@	aurelia-task-queue.js:117
(anonymous function)	@	aurelia-task-queue.js:61**

Just tried the Aurelia + Polymer integration documentation and I ran with this problem. On the image below.

![image](https://cloud.githubusercontent.com/assets/5933437/12869949/cc6302da-ccf3-11e5-98c6-637110b9c602.png)

**Comment by DiegoGallegos4** [comment]
@EisenbergEffect Any tests on this? Ive manages to work with the app perfectly besides that but that error is quite annoying.

**Comment by EisenbergEffect** [comment]
We can't do anything about this until someone explains how to reproduce the bug in a series of simple steps....or creates a simple repro where we can see the problem. The bug report doesn't provide much in the way of information, so it's hard for us to do anything about it.

**Comment by DiegoGallegos4** [comment]
This was reproducing:

1. Edit the skeleton es2016
2. Follow the steps in the **Integrating with other tech** for polymer. 

This is basically. Would it work, uploading the skeleton on my repo?

Greetings

**Comment by DiegoGallegos4** [comment]
This is the code I have.
https://github.com/DiegoGallegos4/aurelia_polymer

I added a couple of views. But most of the code is the boilerplate of running Polymer on Aurelia. 

Thanks in advance

**Comment by DiegoGallegos4** [comment]
As a note: 

Sometimes when I redirect to route then the router returns: **http:/localhost:<port>/undefined**. The only way to go to a valid route again is to reload to home and start from there after a few reloads.

**Comment by EisenbergEffect** [comment]
@DiegoGallegos4 That router issue is separate from this.

@martingust Any idea what could cause this error? @joelcoxokc What about you? I know you two have both looked into this code. I seem to remember something about this in the past. Any ideas?

**Comment by DiegoGallegos4** [comment]
Hi Rob,

Have you found anything regarding these issues?

**Comment by martingust** [comment]
@EisenbergEffect Not sure but it looks like some conflict in how Polymer manipulates the DOM causing the templating loose orientation.

Issue here is with the `if` binding [here](https://github.com/DiegoGallegos4/aurelia_polymer/blob/master/src/app.html#L24). When its value changes to `true` templating trying to insert the view before its `parentNode`which is null. 

When the `viewFactory` replaces the `if` bindings template tag into an anchor [here](https://github.com/aurelia/templating/blob/b8e51df0c2d94254172eca53b66031a37664bc91/src/view-factory.js#L106) is **has** a parent node. But when trying to insert the view later on its parent node is null (here)[https://github.com/aurelia/templating/blob/master/src/view.js#L178].

Hope that can help something.

**Comment by DiegoGallegos4** [comment]
Rob, do you have any updates on the issues? 

Thanks for the effort.

**Comment by joelcoxokc** [comment]
@EisenbergEffect I ran into a similar issue when pointing router-views to layers 

This is outside of polymer, but I can imagine polymer is doing something very similar. 

The issues is, when the viewslot gets bound or created, it calls `this.removeAll()` before inserting  the next view 

So if this happens to the missing ParentNode's viewSlot's parent view 

and the parentNode is never placed back in It's fragment or never re-referenced.

**Comment by joelcoxokc** [comment]
Ignore the Above. My phone posted before I was finished. I'll remove it ASAP

**Comment by EisenbergEffect** [comment]
@joelcoxokc Do you have an idea how to fix it?

**Comment by DiegoGallegos4** [comment]
Is this one a bug? Or incompatibility with Polymer and Aurelia at the moment?

**Comment by nexbit** [comment]
Hi, I had the same bug today, and I have a project built with Aurelia and aurelia-polymer plugin. 
The error happens when I try to call setRoot() for the second time after a successful login (I use something like this: https://github.com/Foursails/sentry)

These errors are raised when the templating engine processes the _router-view_ element in the app root component (the one set by the second setRoot call):
_Uncaught TypeError: Cannot read property 'insertBefore' of null_
followed by:
_Uncaught TypeError: Cannot read property 'firstChild' of undefined_

If you don't use the router, and you don't have a router-view element, the errors are not raised.

These errors occur in aurelia-templating.js, specifically in _insertNodesBefore_ and _getAnimatableElement_ methods..

I just made the following small fix to the `View.prototype.insertNodesBefore` method:
```
    View.prototype.insertNodesBefore = function insertNodesBefore(refNode) {
      var parent = refNode.parentNode;
      if (parent !== null) parent.insertBefore(this.fragment, refNode);  //--> check if parent is defined
    };
```
and now everything works fine.. I don't know if this can impact something else lower in the pipeline, but for what I see everything works as expected.

Please, if anyone else is impacted by this issue, try the above fix by manually editing the aurelia-templating.js file,  and do a thorough test of the app.
Then report back here the outcome, to see if it can be inserted in a pull request..
Thx

**Comment by aurigadl** [comment]
I have the same error, when try to load other template. 
I don't used different library.
The first time load successful the template login.html but when I try to logout and reload the login it broken.
I try to follow the error and I see that Aurelia-templating.js try to delete "animate elements" that doesn't exist but I am not sure. 

[https://github.com/aurigadl/EnvAurAsk.git](https://github.com/aurigadl/EnvAurAsk.git)

**Comment by EisenbergEffect** [comment]
We've done some implementation improvements in this area in our new shadow dom v1 branch. Hopefully it is solved. If not, please create a new issue and attach a simplest possible reproduction.

**Comment by patrick-mackay** [comment]
Hi, although this issue was closed, and I'm not sure about opening a new one, I'd like to add that after the latest update (today), you got similar error if the html template is empty (<template></template>)

Adding a <span></span> inside the template fixes the issue.

16:12:47.363 ERROR [app-router] TypeError: firstChild is null
Stack trace:
compile@http://localhost/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:2462:1
loadViewFactory/</registryEntry.onReady<@http://localhost/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:3109:29
1 aurelia-logging-console.js:54:8
error() aurelia-logging-console.js:54
log() aurelia-logging.js:37
error() aurelia-logging.js:70
processResult() aurelia-router.js:1784
_dequeueInstruction/</<() aurelia-router.js:1737

**Comment by Thanood** [comment]
I just ran into this problem but unfortunately I failed to provide a simple reproduction.
So I'm going with asking this question first:
Under which circumstances would `View.firstChild` be null ([this line](https://github.com/aurelia/templating/blob/master/src/view.js#L215))?

In my app I could solve this by checking for `true && current` in [this line](https://github.com/aurelia/templating/blob/master/src/view.js#L219).

Context:
```javascript
  removeNodes(): void {
    let fragment = this.fragment;
    let current = this.firstChild;
    let end = this.lastChild;
    let next;

    while (true) {
      next = current.nextSibling;
      fragment.appendChild(current);

      if (current === end) {
        break;
      }

      current = next;
    }
  }
```

**Comment by EisenbergEffect** [comment]
It shouldn't ever be null unless there is actually nothing in the view...in which case the developer should have used `@noView()` on their view-model. Perhaps there is something else interfering?

**Comment by Thanood** [comment]
Probably.. I'll try to find out what it is. Thanks for clarifying.

**Comment by Thanood** [comment]
Okay, that was easy after reading your hint. :smile: 

I've got three viewPorts and "fallback" components for empty viewPorts. Kinda like this StackOverflow answer: http://stackoverflow.com/questions/33267980/optional-viewport-in-aurelia

These empty (optional) viewPorts have an empty template which leads to this error. I've seen this before recently and thought it has been solved.

Using `@noview` did not work btw.

**Comment by EisenbergEffect** [comment]
@Thanood Thanks for looking into it. Would you be able to create me a very simple little project that demonstrates the problem? You can attach the file here. I'll be able to look and see if we need to fix something on our end (sounds like we do but I want to understand what is going on).

**Comment by Thanood** [comment]
@EisenbergEffect here you go. It's pretty big, though with all node_modules and jspm_packages.. I guess I could have done without.. :smile: 

Alternative location: https://github.com/Thanood/viewport-issue

Reproduction steps:
* `npm start` (if you use the zip, otherwise of course `npm i && jspm i`, maybe `jspm update`)
* click on `page 2' 
* click back on `page 1'
* watch the console

Change [these two lines](https://github.com/Thanood/viewport-issue/blob/master/src/no-header.js#L3-L4) for easy experiments. To make it work, insert any char between the `<template>` tags. Also uncomment `@noView()` to test that..

[viewport-issue.zip](https://github.com/aurelia/templating/files/339506/viewport-issue.zip)

**Comment by Thanood** [comment]
As additional info: that empty template worked before upgrading to rc1..

**Comment by Thanood** [comment]
@EisenbergEffect Is that project of any help?

**Comment by ohjames** [comment]
I'm seeing this issue to, a really simple use of `<router-view></router-view>` that worked in a beta version of aurelia. After updating to the very latest release I get the `nextSibling` view.

You can see it at [kchomp.co/login], if you try to click either of the `password` links.

**Comment by ohjames** [comment]
Really not doing anything complicated at all in this example, just a `<router-view>` inside of a template that always worked before. The fact something this basic fails is really dispiriting.

**Comment by ohjames** [comment]
I wasn't on quite the latest version of Aurelia, the 1.0.2 RC fixes it (was broke in the 1.0.1 RC). Bit concerning something so fundamental got through.

**Comment by EisenbergEffect** [comment]
If you had that error, you had something unique about your scenario. That didn't occur in any of our tests, apps, products, etc. If you can isolate what made that happen, then we can add a unit test to cover it.

**Comment by HIRANO-Satoshi** [comment]
I have a similar issue reported by @nexbit when I use setRoot() with Polymer. 

```
Uncaught TypeError: Cannot read property 'insertBefore' of null
```

I needed [his patch](https://github.com/aurelia/templating/issues/259#issuecomment-209538915) to repair it. I think this patch should be included in the source tree.

If you are experiencing a similar problem, see [this issue](https://github.com/roguePanda/aurelia-polymer/issues/20).
