### ISSUE TITLE
problem with @children. not syncing the repeating children.

### ISSUE THREAD

**Issue by ppn2** [aurelia/templating#262]
//parent view
```
<template>
    <require from="./child"></require>
    <child heading.bind="'Heading 1"></child>
    <child heading.bind="'Heading 2'"></child>
    <child repeat.for="child of childrenarray" heading.bind="child">
    </child>
</template>
```
//parent view model
```
export class Parent {
    @children("child") items;
    childrenarray = ["Heading 3", "Heading 4", "Heading 5"];
    bind() {
        //items should have 5 items, but it have only first two items. 
        //repeater children are skipped.
    }
}
```

**Comment by EisenbergEffect** [comment]
Thanks for the repro. I will investigate. We are going to be doing some serious work in this area soon to implement Shadow DOM v1. If we don't get it in before that, it will get fixed as part of the Shadow DOM fix updates. I'll see to it personally.

**Comment by ppn2** [comment]
Actually I found 2 more defects!!!.

1. If we use Type parameter in @children attribute (instead of selector) then nothing gets populated in the children. 
2. While using Type parameter in @children, one were to inject parent in the child constructor, a dependency injection error is raised. I don't remember the exact error, but if you need I would be able to reproduce it in plunker. Please let me know. If the @children parameter is selector string, the injection of the parent works fine.

**Comment by EisenbergEffect** [comment]
What do you mean by the type parameter? What is that? It only accepts a selector...it never accepted anything else.

**Comment by ppn2** [comment]
What I meant is the Type of the Children. Looking at the documentation and indeed it does not accept the Type parameter. Actually while I am looking at the aurelia, I was looking at angular 2 as well and the @children in aurelia is very similar to @ContentChildren in angular 2. There you could specify either of selector or Type of the Children. I inadvertently assumed, aurelia also supports that way as well. My bad, please disregard my earlier comments.

**Comment by cehoffman** [comment]
@EisenbergEffect re: the Shadow DOM work. Does that mean **@child** will work in-conjunction with a view model that has **@useShadowDOM**?

**Comment by EisenbergEffect** [comment]
Yes.

**Comment by gautamsi** [comment]
I had this as immediate requirement for my project, I tried to fix it for my project, not sure if this is something anyone would like to use. Adding it here so that anyone interested in scenario can improve upon this or provide alternate. 

problem:
I wanted to track child custom element in my parent custom element. Can not track the custom element as it is inside other element in parent markup. see markup below

```html
<template>
    <div ref="$navBarRoot" class="ms-NavBar">
        <div class="ms-NavBar-openMenu js-openMenu" click.trigger="toggleNavBar($event)">
            <i class="ms-Icon ms-Icon--menu"></i>
        </div>
        <div class="ms-Overlay"></div>
        <ul class="ms-NavBar-items">            
            <content select="office-navbar-item"></content>
        </ul>
    </div>
</template>
```

use case:
* to be able to track `<office-navbar-item>` in above example. There can be any number of this element
* useful in plugins where you know exactly where your child custom element will be

*what worked for me:* (deep level finding using getElementsByTagName and iterate all elements in the result and check element.matches with sleector. )

* `@children('office-navbar-item', true /* deep */)` find first deep level match, select all its sibling, ignore rest
* `@child('office-navbar-item', true /* deep */)` find any first deep level match, ignore rest.

known issues (of my code):
* still has issues and undesired result in some cases, but if you know what you are looking for, you can improve this code. 

improvement:
* I think it can be improved by using Nth child or up to Nth child lookup in parameter. this way some of the undesired results can be ignored. 
* request to @AureliaEffect  - can Nth child parameter be provided to `@child` or `@children`  using bindable attributes? 




my changes to child-observation.js https://github.com/gautamsi/templating/commit/d2c1232c7d1988906a410240b97431f6af90165a#diff-cfe3cd91e804c7b04a7d3535ca671bf1

**Comment by EisenbergEffect** [comment]
New implementation preparing to launch inline with shadow dom v1 slots.
