### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by ppn2** [aurelia/templating#274]
This is a weird bug which happens on a specific situation only. The best way to understand the issue is to see it in the plunker.

[http://plnkr.co/edit/6S4yKh?p=preview](http://plnkr.co/edit/6S4yKh?p=preview)

This plunker is almost reproduction of the aurelia getting started tutorial, but has a few changes.
1. I have removed the http call on the users.js. Instead I am populating the users collection inline. There are only two entries in the users collection.
2. There is an collection observer on the users object in users.js.
3. I have written a very simple custom component (comp.js) and is being used by the users.html in a repeat loop.

The way to reproduce the issue is to kick off the plunker. You would see Welcome screen with Welcome and Users link at the top. Visit users link. As expected you would see two records (As I have two records in the users collection). Now visit the Welcome link and come back to the users page again. Now you would see 4 records. Seems like aurelia is keeping the references from the earlier visit to the users page.

There is a bind function in the comp.js, which is empty and does nothing. The weirdest part is, If you remove that function and repeat the above scenario, everything works as expected and you will see only 2 records.

Also if you remove the observer from the users collection in users.js (while bind function is present in comp.js), everything works as expected.

**Comment by martingust** [comment]
@ppn2 I get 404 on the link

**Comment by ppn2** [comment]
Sorry about that. Can u please try now.

**Comment by EisenbergEffect** [comment]
Thanks for looking into this @martingust !!!

**Comment by jdanyow** [comment]
I've been burned by this in the past:  when testing for mem leaks, be sure to clear the console... logging to the console produces memory leaks (when the console is open)

**Comment by martingust** [comment]
@ppn2 The issue here is that the array is being subscribed on and mutated in the same loop **before** the `repeat` is bound. This is causing the `repeat` to bind with the two values and also receiving a change event with the same items, and thus they get duplicated. 

There are some fixes in the next binding release which might fix this. 

You could also fix this by queuing up the `splice` call on the microtask or do it all in a  later life cycle event like `attached` or `activate` like here https://gist.run/?id=b1cd898fe6d646dbcf08
