### ISSUE TITLE
$parent and binding-context of custom element and its content children are the same. 

### ISSUE THREAD

**Issue by MikaelPorttila** [aurelia/templating#276]
Hi I'm having trouble accessing the parent custom element(A) when using $parent on children custom elements (B).
Instead of getting the parent custom element(A) as bindingcontext i get the same binding context as the parent.

```javascript
// a.html
<template>
	<content></content>
<template>

//a.js
export class A {
	foo() { ...method never called... }
}

// b.html
<template>
	<button click.delegate="$parent.foo()"> /* <-- This $parent will never be A, instead i get the parent context of A  */
<template>


// awesomeapp.html
<a>
	<b></b>
	<b></b>
	<b></b>
</a>
```

**Comment by jdanyow** [comment]
A custom element template doesn't have access to anything outside of it's own binding context. This is intentional and ensures custom elements are portable and encapsulated.  If the example you posted above were supported that would mean the `<b>` custom element only works when used within something that exposes a `foo` method as opposed to something like an `<a>` element that works anywhere.

To resolve the issue add a `@bindable` property to the `b` element:
```js
@bindable foo;
```

then when using `<b>` do this:

```html
<b foo.call="foo()"></b> <!-- $parent is not needed -->
```
