### ISSUE TITLE
Binding attributes for custom elements without using @bindables decorator

### ISSUE THREAD

**Issue by ArunaSelvaraj** [aurelia/templating#278]
Shall I know how to add attribute like header, sortable, etc., to our custom elements either without  @bindables or by using loop for bindable decorator using a single line bindable.

I have array that consist of these properties!

I simply do not want to write a lengthy @bindable('propname') for each one and not to have @bindable('prop1','prop2').

Plz give me solution ASAP .

**Comment by EisenbergEffect** [comment]
@ArunaSelvaraj Please don't ask for help ASAP. My team works very hard on many things. We address issues according to priorities as soon as we can. If you have a question rather than a bug or feature, the best place to get that help is in our gitter chat room. gitter.im/aurelia/discuss.

That said, try this:

```
export class MyClass {

}

['prop1'. 'prop2'].forEach(prop => bindable(prop)(MyClass));
```

*Decorators are just functions that are applied to the target.*
