### ISSUE TITLE
if.bind reorders template content

### ISSUE THREAD

**Issue by nicolasdejong** [aurelia/templating#280]
When using a template (in *testpanel.html*) that only contains a `<content></content>` and an empty class called `TestPanel` (in *testpanel.js*) the following input:

```html
<test-panel>
  <div>A</div>
  <div if.bind="true">B</div>
  <div ib.find="true">C</div>
  <div>D</div>
</test-panel>
```

ends up in the DOM as follows:

```html
<test-panel>
  <div>A</div>
  <div>D</div>
  <div>B</div>
  <div>C</div>
</test-panel>
```

It seems something is wrong with the text-nodes that appear to be used to figure out where to put back the bound elements. I looked through the aurelia-templating.js source code but everything there is rather complicated so didn't find out where the problem lies exactly.

Workaround now is to either use an if.bind on every immediate child of test-panel (using 'true' for those that won't need an if) or using a class to hide the divs that should not be shown.

Is there any other possible workaround that does not require the user of my template to know these details?

**Comment by EisenbergEffect** [comment]
We are aware of this issue. It's a consequence of the way that our shadow dom fallback implementation is implemented today. We are tracking it already and plan to have a fix as part as our update to Shadow DOM v1 slots.

You can follow the issue here: https://github.com/aurelia/templating/issues/250

Thanks for your patience.
