### ISSUE TITLE
if.bind on <template> works in FireFox but not in Chrome

### ISSUE THREAD

**Issue by opcodewriter** [aurelia/templating#299]
Please see example 
https://gist.run/?id=0ec28f7c36833e2508c1
Look to `click-to-edit.html`
```
<template>
  <button click.trigger='clicked()'>Click Me</button>
  <template replaceable part="item-template" if.bind='isVisible'></template>
</template>
```

You shouldn't see the text "This text node is in DOM only after click " at start, but only after clicking the button. 

It works in FireFox but not in Chrome.

**Comment by opcodewriter** [comment]
it's been 11 days...

**Comment by EisenbergEffect** [comment]
Apologies for the delay, we've been very busy lately dealing with jspm and Babel updates, system.js alternatives and polyfill improvements.

With respect to this issue, try something out for me: remove the "replaceable" attribute from your if template and see if it starts working. I think that might do it. If it does then you have a workaround and we know what the issue is.
