### ISSUE TITLE
Vanishing elements when used with Polymer

### ISSUE THREAD

**Issue by robinchesterman** [aurelia/templating#322]
When using Polymer elements with Aurelia repeater (and perhaps in other scenarios), elements vanish when clicked:

`<link rel="import" href="../lib/paper-listbox/paper-listbox.html">
<link rel="import" href="../lib/paper-item/paper-item.html">
<template>
	<paper-listbox  class="dropdown-content" multi>
    	<paper-item repeat.for="item of items">${item}</paper-item>
    </paper-listbox>
</template>
`
Example plunker: http://plnkr.co/edit/frI6XWGIcPrQiXOLGYAb 

This was described on the gitter channel as

"aurelia is parsing the html for custom elements and replacing them, it seems,but there isn't a custom element that matches, but it is still getting replaced"

**Comment by robinchesterman** [comment]
Not a lot of love for this issue it seems, but it's really giving me a hard time!

**Comment by EisenbergEffect** [comment]
Can you create a simple sample on the skeleton that we can easily install and run locally to take a look?

**Comment by robinchesterman** [comment]
Sure - I thought the plunker was an easier way of showing it as simply as possible, but happy to try and repro on the skeleton.

**Comment by EisenbergEffect** [comment]
I can see it happening. My guess is that it's something strange about the polymer controls themselves. Notice that it's either a left or right mouse click. I'm wondering if they re-arrange the dom and rely on some events that are getting interpreted differently somehow.

**Comment by robinchesterman** [comment]
I put it on the welcome page of the TypeScript skeleton:

https://github.com/robinchesterman/AureliaPolymer/tree/master/skeleton-typescript

Sorry - I included jspm_packages in the repository, just because there's a little bit of faff involved in getting polymer installed via jspm via bower. Hopefully this will just work.

**Comment by dpinart** [comment]
I usually have issues when using repeat.for within polymer "list" controls. If you create a custom behavior and attach it to the paper-list box will see despite the html tree shows the paper-list-box contains three paper-items the paper-list-box object (you can get it injecting the element on the behavior constructor) has its items properties empty. I haven't tested the same scenario you showed in the plunker, my scenario loads items asynchronously from the backend. I guess that polymer "list" controls do not handle children added to the dom at runtime

**Comment by EisenbergEffect** [comment]
@dpinart That would be my assumption as well. They probably can't handle any scenario where a child is dynamically added or removed.

**Comment by dpinart** [comment]
There are 2 options to dynamically add items to polymer 'list' controls like paper-list-box, paper-toolbar,...
1)Create a behavior that attaches to the polymer control and gets the list of children items as a bindable property and write 'polymer' javascript to add/remove items to the container control. Never used it but it should work. The  bad thing is that is a bit tedious and can't figure out how to add aulirea stuff like behaviors, bindings,... to the new added html items
2)Use aurelia's compose. Yous sholud create a viewModel that gets the list of children at activate handle via compose.model attribute, override the getViewStrategy method and build dyamically the inline template. I'm using this strategy in a couple of views and it's working really nice. I did a hack in order to being able to recreate the view if the list of items changes. Anyway I think you can face performace issues if you add/remove items quite often. Following link might be interesting https://github.com/roguePanda/aurelia-polymer/issues/17
