### ISSUE TITLE
How to defer Aurelia lifecycle invocation when you also need a <content> element (cannot use if.bind). 

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#337]
@EisenbergEffect I had a conversation with you on Gutter concerning how I can defer a section of my DOM, being the inner html of a custom element, from being activated by Aurelia until I want it to be activated.

By "activated" I mean that part of the DOM not instantiating its view model objects, not executing the lifecycle methods, no binding, etc. Functionally it's like what happens when you put a custom element in a template but forget the require element for it.

The application is a tab control. The tab page content of a particular tab must not activate until such time as the tab is first made visible. Imagine you had 15 tabs each with a data list component on it - it is wasteful loading 15 lists of data upfront if the user is never going to look at that tab page.

You suggested if.bind and for a regular situation that does the job perfēctly.

But if you think of a tabpage custom element and what its template might be,  it is not much more than a lightweight container for tab page "content" injected using the &lt;content&gt; element, wrapped by  a means to show or hide that content. In my case show.bind and if.bind are employed on two outer divs, with the content element inside that.

It should be a no brainer except it doesn't work.

Unfortunately if.bind cannot be used with &lt;content&gt; because no content is ever shown. Another issue that I found on here says this is the result of how Shadow DOM works.

Do you have any suggestions on how to achieve my objective?

**Comment by EisenbergEffect** [comment]
You could process the content of each tab item, adding a wrapper div to the end user's content. The wrapper would container the if.bind against the active tab. In this way you conditionally evaluate the content itself and the content projection element <content> remains statically defined.

You may consider using a special custom attribute instead of if...perhaps a lazy attribute that doesn't create the view until it first becomes true but just hides things when it becomes false.

Does that make sense?

**Comment by kevmeister68** [comment]
You've just described my workaround as I currently have it!  It's also the reason for many questions about processContent() :-) 

Do you foresee having a better way to solve this in future?

**Comment by EisenbergEffect** [comment]
The trick is determining if there's a general issue and seeing how we can improve that while still maintaining the constraints I talked about in the other issue as well as our need to support shadow dom (which does create its own issues). Outside of tabs, are there other use cases you can identify where this is needed?

Another idea is to use process content to separately compile the consumer's content into a view factory. Attach that view factory to the instruction so it can be received by the tab item in its constructor. Then, inside the tab item element, simply create the view when the tab is activated. You can use the bind hook to grab the bindingContext and overrideContext so that you can bind the child view with the same scope.

This would avoid the use of the extra element and let you control the instantiation, showing, caching of the tab item content directly. However, it wouldn't work with the shadow dom, but wouldn't be necessary. You could just use `noView` on the tab item and have a ViewSlot injected so you can dynamically render its own view based on the end user content. Does that make sense?

**Comment by atsu85** [comment]
@kevmeister68, 
> By "activated" I mean that part of the DOM not instantiating its view model objects, not executing the lifecycle methods, no binding, etc
...
> The application is a tab control. The tab page content of a particular tab must not activate until such time as the tab is first made visible. Imagine you had 15 tabs each with a data list component on it - it is wasteful loading 15 lists of data upfront if the user is never going to look at that tab page.

I accomplished this (tabs control that didn't activate tab before making it visible) with compose element:
```html
<div if.bind="activeTab">
    <compose model.bind="commonModelForAllTabs" view-model="./${activeTab}/${activeTab}"></compose>
/div>
```
I pass only some common data model for all tabs (`commonModelForAllTabs`) and load tab-specific content when the tab is activated.
As You can see here, I've created a subfolder for each tab, that contains custom element (js and html with the same name as the folder name) and when the tab is clicked i update `activeTab` property that then triggers activation of the correct custom element that is used as tab content. Then the custom element lifecycle kicks in that give You a chance to load tab-specific data from the server to be shown in tab content.

I know that my use-case is not exactly what You initially had in mind:
> how I can defer a section of my DOM, being the inner html of a custom element, from being activated by Aurelia until I want it to be activated.

...but just maybe You don't need that anyway to achieve the main goals (the first 2 quotes of You in the beginning of my reply).

Anyway it has worked for me really well and it was no-brainer to implement it :) (also in a very flexible way, for example to 1) decide what tabs to show 2) what tab to activate by default, if one needed to be activated by default)

**Comment by kevmeister68** [comment]
@atsu85 Thanks for the suggestion. I know there are numerous "workarounds" (I have my own also), but I am focused on a solution that is *elegant* from the perspective of the component user. My fundamental objective from the outset has been to have a tab control that was easy to "consume" by a user of it. I wanted the HTML to look like this:

    <ui-tabcontrol>
        <ui-tabpage>
            <tab-heading>
                Details
            </tab-heading>
            <tab-content>
                More Aurelia-stuff.
            </tab-content>
        </ui-tabpage>
    </ui-tabcontrol>

There are plenty of workarounds to get the outcome, but I want to get the nicety of the implementation *and* the outcome.

**Comment by kevmeister68** [comment]
Sorry it's taken me a while to respond. I don't think there are a huge number of examples that "need" the functionality I am proposing, but widgets such as tab controls, accordions, and wizards all come to mind as UX constructs that _may or may not_ actually use a given UX "sub-element" (eg. tab-page, accordion page, wizard page etc).

Other than that, your suggestion makes sense. The only downside is complexity. 

When you say inject the ViewSlot do you mean actually @inject the ViewSlot and then inject the view into that slot when required?

I'm all for simple things being simple to do and all that, I'm not sure if this overly complex for the user case.

Which brings me to another question - is there any plans for a <content> type element that doesn't involve Shadow DOM. I know that might be the wrong question, as the right question might be having a <template> which doesn't end up in shadow DOM, and a <content> tag that works in that "mode"?

**Comment by EisenbergEffect** [comment]
Any component that has both a view and end-use content, requires shadow dom otherwise there's no way to produce the final rendered output. Somehow the content tree and the view tree need to be merged. That's what shadow dom does. However, if you don't want that, you can simply put the `@noView()` decorator on your component and Aurelia won't invoke the templating engine to render a view for your component. Instead, you could process your own content and decide how to render your component.

You can use `@inject(ViewSlot)` on any component to get a ViewSlot which points at the content of the custom element. You can then `viewSlot.add(view)` to adds views into that content of your element. You get `View` instances from calling `create` on a `ViewFactory`. You get `ViewFactory` instances from calling `compile` on the `ViewCompiler`. So, you could have a custom implementation that uses the `processConetent` hook to grab it's content and pass that to the `ViewCompiler` to compile a `ViewFactory`. You could then store that on the instruction object that is passed to the `processContent` decorator. This allows you to cache your compiled view factory for later use because you can later `inject(TargetInstruction)` into your component and retrieve the factory you generated. You can then use that factory to create views and push them into the slot at will. It's not that complicated. Let me see if I can whip up an example.

**Comment by EisenbergEffect** [comment]
```javascript
@noView()
@processContent(compileTabContent)
@inject(Container, ViewSlot, TargetInstruction)
export class TabItem {
  @bindable isActive;

  constructor(container, viewSlot, instruction) {
    this.container = container;
    this.viewSlot = viewSlot;
    this.contentFactory = instruction.elementInstruction.contentFactory;
  }

  isActiveChanged(newValue) {
    if (newValue) {
      if (this.view) {
         //todo add a class to show the view
        this.ensureBound();
      } else {
         this.view = this.contentFactory.create(this.container);
         this.viewSlot.add(this.view);
         this.ensureBound();
      }
    } else if (this.view) {
      //add some classes to hide the view
      this.view.unbind();
    }
  }

  bind(bindingContext, overrideContext) {
    this.isBound = true;
    this.bindingContext = bindingContext;
    this.overrideContext = overrideContext;
    this.ensureBound();
  }

   ensureBound() {
     if (this.view && this.isActive && this.isBound) {
       this.view.bind(this.bindingContext, this.overrideContext)
     }
   }

  unbind() {
    this.isBound = false;

    if (this.view) {
      this.view.unbind();
    }
  }
}

function compileTabInstruction(compiler, resources, node, instruction) {
  let fragment = DOM.createDocumentFragment();
  //consider adding a div to wrap the user content so it's easier to hide show

  while (node.firstChild) {
    fragment.appendChild(node.firstChild); //copy the content of your element into a fragment
  }

  instruction.contentFactory = compiler.compile(fragment, resources); //compile the fragment
}
```

**Comment by kevmeister68** [comment]
Thanks Rob, I will experiment with this. Your two posts above have probably been amongst some of the most enlightening posts I have read that enable me to understand Aurelia better.

**Comment by EisenbergEffect** [comment]
Note that I didn't test the code above...just wrote that up directly in github, but it should give you a good start.
