### ISSUE TITLE
aurelia-dialog no longer works with out-of-band v2.0.0

### ISSUE THREAD

**Issue by jsobell** [aurelia/templating#358]
The body of dialogues sourced from aurelia-dialog are now empty.
I assume we need a 2.0.0 of aurelia-dialog too?

**Comment by EisenbergEffect** [comment]
None of the plugins have been updated to the new shadow dom implementation since it's out-of-band and we don't want to break everyone on that. For now, you can fix the issue by diving into the source of the dialog's html files and changing each `<content>` element to a `<slot>` element. The dialog.html uses `select` which isn't part of the spec, but you could just replace those three with a single `<slot>` because that should work as long as you put your header, body footer in the right order, which makes sense anyway.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/dialog #156](https://github.com/aurelia/dialog/issues/156) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by jsobell** [comment]
Ah, multiple `<slot>`s without a name!!!
I tried to change it using named slots yesterday but had no luck.
Thanks for that
