### ISSUE TITLE
view.fragment not "public"?

### ISSUE THREAD

**Issue by glen-84** [aurelia/templating#370]
I'm using code like this:

```ts
    const resources: ViewResources = aurelia.container.get(ViewResources);

    resources.registerViewEngineHooks({
        afterCreate: (view) => {
            $(".js-date-picker", view.fragment).datepicker();
        }
    });
```

But there is no type information for `view.fragment` – is it possible to add this?

**Comment by EisenbergEffect** [comment]
We don't want to make every property part of the public API, otherwise it makes it hard for us to change things without breaking people, which we may need to do if we find more performant internal implementation ideas. That said, I've added a few of the most important properties to the public API, including `fragment`.
