### ISSUE TITLE
Slots inside an if.bind

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#389]
We're having a bit of doubt on whether or not slots should work inside an `if.bind`:

```
  // app.html
  <require from="./c-element"></require>
  <c-element>
    <div slot="firstText">
      firstText
    </div>
    <div slot="secondText">
      secondText
    </div>
  </c-element>
```

```
// c-element.html
<template>
  <div if.bind="true">
    <!-- this slot doesn't work -->
    <slot name="firstText"></slot>
  </div>
  <div>
    <!-- this one does -->
    <slot name="secondText"></slot>
  </div>
</template>
```

This is shown:
![image](https://cloud.githubusercontent.com/assets/2189477/16092877/dff77ae0-3339-11e6-8567-b5bc2c5cc19e.png)

repro: https://github.com/JeroenVinke/slot-if-bind

We think that this should work because of the following quote in the blog:
>  All the above is implemented with Aurelia. It also works with template controllers such as if and repeat which can dynamically generate content.

But we're not sure because this is mentioned as well:
> However, slots do not solve the problem of replacing a template that is used by a repeat, if or other template controller.
>  You can still add a "part" attribute on repeater, if, with, etc to replace the template that is used by those, since that's not compatible with slots.

**Comment by EisenbergEffect** [comment]
No, a slot inside of an if.bind cannot work because slots themselves have to be statically known. However, content used inside that element, which is conditionally added/removed by an if bind will correctly project into the slots.

**Comment by atsu85** [comment]
@JeroenVinke, would You like to help to implement the check for template linter that You discussed here? I've created two tests regarding using slots with template controllers: 

1) [test that has template controller inside slot](https://github.com/atsu85/aurelia-template-lint/commit/4a5c66d19201b1fcf08928ca578de027530daf63#diff-fa0e0cc88c52bc15a5a1ff71151bf248R47) already passes 

2) [test that has slot inside template controller](https://github.com/atsu85/aurelia-template-lint/commit/1f1bd9b6eef60425a8b083cfb1c3ead72d72e1ce#diff-fa0e0cc88c52bc15a5a1ff71151bf248R60) fails right now, because SlotRule (in [slot.ts](https://github.com/MeirionHughes/aurelia-template-lint/blob/master/source/rules/slot.ts)) doesn't check the presence of `if.bind` attribute (or any other template controller attributes, such as `repeat.for`) on ancestor elements.

**Comment by Thanood** [comment]
A template linter? What a great idea! :+1:

**Comment by atsu85** [comment]
Yeah, it is quite useful already - catches lots of bugs me and my teammates have stumbled upon :)

**Comment by sickboy** [comment]
Also ran into this one :)

**Comment by Ma3yTa** [comment]
@EisenbergEffect @jdanyow How to resolve it if need to remove slot content from DOM by if.bind?

**Comment by EisenbergEffect** [comment]
You can't have slots inside an if.bind. Consider using show.bind instead or use template parts.
