### ISSUE TITLE
Custom element slot not rendering inside a table

### ISSUE THREAD

**Issue by tochoromero** [aurelia/templating#433]
I'm trying to create a very simple data grid using custom elements, but I cannot make it work.

When I try to get the <slot></slot> to project the content inside a <table></table> it just renders the content right at the beginning of the template. This is a simplified version of what I have:

```html
<!-- home.html -->
<template>
  <require from="./grid"></require>
  <require from="./column"></require>

  <grid>
    <column>Value for first column</column>
    <column>Value for second column</column>
  </grid>
</template>

<!-- grid.html -->
<template>
    <table class="table table-stripped">
        <tbody>
        <tr>
            <slot></slot>
        </tr>
        </tbody>
    </table>
</template>

<!-- column.html -->
<template>
    <td>
        <slot></slot>
    </td>
</template>
```

With this code when the custom elements get render I end up with this:
```html
<grid class="au-target" au-target-id="4">
    <td>Value for first column</td>
    <td>Value for second column</td>
    
    <table class="table table-stripped">
        <tbody>
        <tr></tr>
        </tbody>
    </table>
</grid>
```
As you can see the content gets rendered outside the table element. 

The interesting part is that if I change the grid.html to this:
```html
<!-- grid.html -->
<template>
    <table class="table table-stripped">
        <tbody>
        <tr>
            <td>
                  <slot></slot>
            </td>
        </tr>
        </tbody>
    </table>
</template>
```
Then the slot gets rendered in the right place, so I wonder if the browser is doing a weird thing where it thinks the whole table structure is invalid and moves the content outside of it.

Btw, this is with the latest version of Chrome in OSX

**Comment by saibot777** [comment]
tochomero, I have the same problem, did you manage to solve this

**Comment by tochoromero** [comment]
I took a different approach. But I believe this can be solved with the `as-element` attribute
http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-basics/5

**Comment by saibot777** [comment]
Thanks brah, your approach gave me an idea

**Comment by tochoromero** [comment]
@saibot777 If you looking for a grid plugin, you may want to take a look at my plugin. It may do be what you need https://tochoromero.github.io/aurelia-table/

**Comment by rafatpc** [comment]
Guys, have anyone managed to fix that issue?

**Comment by valery-vitko** [comment]
Another workaround is to have a separate container element with custom parts you need in your grid component. You can pass it as a whole via a slot to the component. Then you re-attach DOM elements from this "customization" container to the actual data table where you need them. Here's a sample with thead/tfoot customization support: https://embed.plnkr.co/GB4alF.

Although this solution can be (in theory) stretched to solve the original issue in full, I actually used this myself in combination with approach @tochoromero proposed. I passed cols/rows to a custom grid component as data, but used markup-based headers/footers since they were unique per-table and quite complex.
