### ISSUE TITLE
Trying to load view for ValueConverter if there is more than one export from file

### ISSUE THREAD

**Issue by fracz** [aurelia/templating#511]
**I'm submitting a bug report**

* **Library Version:**
1.1.4

* **Language:**
all 

**Current behavior:**
The following value converter declared in `upper-value-converter.js` [works](https://gist.run/?id=249c55563cfe3d868cddbfcb902a9fb2):

```
export class UpperValueConverter {
  toView(sth) {
    return sth.toUpperCase();
  }
}
```

However, if you add another export from this file, aurelia tries to load `upper-value-converter.html` which [breaks the application](https://gist.run/?id=e908ddbf4f6687382ca1de9b121fe598):

```
export class UpperValueConverter {
  toView(sth) {
    return sth.toUpperCase();
  }
}
export class ConvertedValue {}
```

Making the first export `default` does not help. Adding the `upper-value-converter.html` helps, but it is not used.

**Expected/desired behavior:**
It should be possible to define and export other classes in the same file where the value converter is.

Rationale: I would like to define input & output values as classes and it seems reasonable to put them in the same file.

**Comment by jdanyow** [comment]
When a module is imported using `<require from="./upper-value-converter"></require>`, the [ModuleAnalyzer](https://github.com/aurelia/templating/blob/master/src/module-analyzer.js) classifies each of the exports as a custom element, custom attribute, value converter, etc. Basically everything is assumed to be a custom element unless it fits one of the naming conventions or has an explicit resource type defined via a decorator (eg `@customAttribute('foo')`).

Will need @EisenbergEffect to confirm but from what I know of the system I don't think it's possible to mix resource exports (custom elements, attributes, converters, etc) with plain old class exports unless some sort of `@notAResource` decorator is introduced.

One thing you could do is skip exporting the `ConvertedValue` class but I doubt that will be helpful for you. If you're using typescript you could use an interface instead (`export interface ConvertedValue`) because they are transpiled away.

**Comment by EisenbergEffect** [comment]
Yes, you don't want to export non-UI items from a UI-related module. When you use `require`, it will try to interpret those exports in terms of the templating engine.

**Comment by fracz** [comment]
Ok, I supposed it is forbidden because of technical stuff.

But have you seen that it breaks also when you [mark the export as default](https://gist.run/?id=00e32ce7f5d84843b3b9e93439244be3) (i.e. `export default class UpperValueConverter`)?

**Comment by EisenbergEffect** [comment]
That sounds like a case that we should handle. The problem with marking something as default is that that changes the export name. I'm not sure if we can support it with naming conventions or not. Can you create a separate feature request to support default exports?
