### ISSUE TITLE
Race condition in InlineViewStrategy / <compose>

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating#544]
* **Browser:**
Chrome 57

**Current behavior:**
When binding a `<compose>` to an `InlineViewStrategy` and replacing the strategy a couple of time in quick succession, the final state may vary. See https://gist.run/?id=786a81fa21a427cd803d1ee1e12681d0

**Expected/desired behavior:**
Regardless of how long it takes, `<compose>` should eventually settle on the last state of the `InlineViewStrategy`.

**Comment by RomkeVdMeulen** [comment]
May be related to #538.

**Comment by StrahilKazlachev** [comment]
I could not debug the repro locally since it always shows **3** for me. In gistrun though on first run I always get **2**. I think the issue is that `<compose>` does not await the call to `CompositionEngine.prototype.compose`(in [processInstruction](https://github.com/aurelia/templating-resources/blob/62ba417aacd4f1b12830d73de79e676e273386d5/src/compose.js#L186)) to finish before calling it again. So it all depends on which call will complete last. I'm unsure if not awaiting is *intended* or *not*. But you could also get this issue if one of the *previous* VMs takes longer in its `.activate` hook than the next ones.
@RomkeVdMeulen I don't think #538 is responsible for this issue, but it could help with its manifestation.
@EisenbergEffect If you are OK with the above explanation could you move the issue to `templating-resources`? I'll also open a PR.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating-resources #299](https://github.com/aurelia/templating-resources/issues/299) via [**ZenHub**](https://www.zenhub.com/)
