### ISSUE TITLE
Error when having `slot` attribute on `<slot>`

### ISSUE THREAD

**Issue by niclassahlin** [aurelia/templating#566]
**I'm submitting a bug report**

* **Library Version:**
aurelia-templating 1.5.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6

* **Node Version:**
7.10.1

* **NPM Version:**
4.2.0

* **Browser:**
Chrome 63.0.3232.0

* **Language:**
TypeScript 2.5

**Current behavior:**
Error `TypeError: Cannot read property 'isInitialized' of undefined` when projecting a slot into another slot, i.e.

```html
<mixed-slot>
    <slot name="slot1" slot="slot1">Fallback Content for Projected Slot 1</slot>
    <slot name="slot2" slot="fallbackSlot2">Fallback Content for Projected Slot 2</slot>
</mixed-slot>
```

Reproduced in [niclassahlin/aurelia-templating-bug](https://github.com/niclassahlin/aurelia-templating-bug).

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect The issue is caused from 2 things as far as I can tell, don't know which is the problem.
1. The refactoring of the `BindableProperty.prototype._configureDescriptor` in [Inherit Bindable Properties](https://github.com/aurelia/templating/pull/507/files#diff-73c2c03482330e771b172983de3bfd75R4526) - the behavior is no longer passed in, but acquired using [metadata.get](https://github.com/aurelia/templating/pull/507/files#diff-73c2c03482330e771b172983de3bfd75R4471).
2. `SlotCustomAttribute` has no `HtmlBehavior` associated with it - don't know whether this is a bug that's been unnoticed till know because of how `BindableProperty.prototype._configureDescriptor` was implemented or it is by design.

Decorating `SlotCustomAttribute` with `@customAttribute()` does *seem* to solve the issue, but if that is a *fix* depends on whether **2.** is by design or not.

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev I think the missing behavior may have been an unnoticed bug. Do you have time to add that and perform a few tests to ensure that everything is working as expected?

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect Yes, I'll see what I can do.
