### ISSUE TITLE
make the <!-- view --> comments optional in the DOM

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#57]
Currently the templating will create  comments in the dom.
it would be nice if this can be disabled so that can also get out of your way as @Aedaeum [pointed out](https://gitter.im/Aurelia/Discuss?at=552d5dae0e3138bb6be81ccc).

if @EisenbergEffect can confirm these are not "needed" i wouldn't mind creating a PR to make them optional , perhaps using a `createComments` boolean property on the `ViewCompiler`.

**Comment by EisenbergEffect** [comment]
Something is needed, otherwise it gets extremely difficult to tell where one view instance begins and ends, particularly in the case of repeaters and other similar constructs. Imagine you want to remove a "view" from the DOM? What if the first or last thing in that view is a repeater that generates more DOM at the beginning or and of the View. Now, how do you know where the "line"is that dilineates one view from another?

I'm open to other solutions, but this seems the simplest and most performant way to handle the situation. Anyone iterating the DOM should be checking for a particular node type, so I'm not sure how this would really cause a problem.

**Comment by danielabar** [comment]
I'm running into an issue with the generated view comments where svg is not rendering because of them. (let me know if I should open a separate issue). 

I have a custom graph element that builds the svg closing and opening tags (and the viewModel handles the graph model and overall graph operations):

```html
<template>
  <require from="../node/node"></require>
  <svg width="${presentationSVG.width}" height="${presentationSVG.height}">
    <node repeat.for="displayNode of displayNodes" data.bind="displayNode"></node>
  </svg> 
</template>

Then each node in the graph is implemented as a containerless custom element. The idea being each node will provide its own behaviour like figuring out its size, what color it should be, click, drag, animation behaviour etc. And eventually will also be edge custom element.

```html
<template>
  <circle cx="${node.x}" cy="${node.y}" fill="${node.color}" r="${node.size}"></circle>
</template>
```

The problem is the generated view comments such as:

```
<!--</view>--><!--anchor--><!--</view>--><!--<view>--><!--<view>-->
```

are preventing the svg circles from rendering. If I manually remove the comments in dev tools, then the circles are shown.

Is there a solution to this?  Or do I need to find a different way to structure the graph, like putting all the node and edge logic in the graph viewModel itself, and can't split out into node and edge elements?

**Comment by jdanyow** [comment]
@danielabar would you mind setting up a reproduction of this in the [aurelia plunker](http://bit.ly/aurelia-plunker)?

**Comment by danielabar** [comment]
@jdanyow Sure will try to reproduce. Haven't used aurelia plunker before, should it be displaying the 'hello world' message by default? It looks blank.

**Comment by jdanyow** [comment]
It should display "loading..." and then "hello world".  Try refreshing, sometimes plunker can be slow.

**Comment by danielabar** [comment]
Ok now see the message, sorry if its a silly question, but am I supposed to edit that plunker directly or fork to my account?

**Comment by danielabar** [comment]
[Here's a demo](http://plnkr.co/edit/LyzHBQ?p=info) of the problem.

**Comment by EisenbergEffect** [comment]
I don't see how the comment nodes would break rendering. If that did, it would appear to be a browser bug. The presence/absence of comments shouldn't be causing this. If it truly is that, I would need to see an SVG spec reference that states this is illegal otherwise we would want to submit this as a bug to the browser.

Looking at your code though, it looks like you may not be creating your custom svg element correctly. The view template for the custom svg element should also contain an svg element, per the docs. See the section on SVG Elements here: http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/cheat-sheet

**Comment by danielabar** [comment]
That was the problem, didn't realize need another nested `<svg>` tag in the custom node element. Adding that, now the circle renders. And it solves another issue I was having where the `cx` and `cy` attributes weren't binding to the node data attributes. Now that works as well (made the example a little bit more in the direction I want to go, processing a list of nodes).

Thank you so much!

**Comment by EisenbergEffect** [comment]
You are welcome. We will try to make this more clear in the upcoming, more extensive documentation on templating.

**Comment by Esger** [comment]
The 'view' and 'anchor' comments cause the CSS `+` (adjacent sibling) selector to fail.
