### ISSUE TITLE
Can't get property from view model in repeater

### ISSUE THREAD

**Issue by rehanhilmy** [aurelia/templating#656]
**I'm submitting a bug report**

* **Browser:**
| Chrome 71 | Firefox 64.0.2 |

* **Language:**
 TypeScript 

**Current behavior:**
I can not get a value (selectedThing) from view model (app.ts) within a `repeat.for`.

**Expected/desired behavior:**
Access a property from the view model in a repeater.

**Reproduce problem:**
I attached an archive with a simple Aurelia project: [Archiv.zip](https://github.com/aurelia/templating/files/2808448/Archiv.zip)

There I check if something is selected with `${thing == selectedThing ? 'selected' : ''}` in app.html. So that, if one thing is selected, its background color will be changed. However, this doesn't work.

Two possible work-arounds are:
1. Add @bindable for selectedThing in app.ts.
2. Write `${selectedThing}` somewhere else in app.html.

**Comment by bigopon** [comment]
@rehanhilmy Thanks for filing this, what you encountered is an expected behavior, not a bug. By default Aurelia binding system traverses the scope tree to find a matching property to observe. The scope tree in your cases comprises of repeat item and the app instance. It traverses from repeat item to app instance.

- If the app instance does not have property `selectedThing`, the binding system fallbacks to repeat item scope, as it assumes that it's the intended scope. The binding system then starts observing the `selectedThing` property on **repeat item**, which will make it not displaying any changes when you click on any item, because the click handler assign `thing` to `selectedThing` on app instance.
- If the app instance has property `selectedThing`, the binding system can find it and decides app is the intended scope. The binding system then starts observing the `selectedThing` property on **app instance**, which will make it start to behave the way you want.

> Write ${selectedThing} somewhere else in app.html.

When you did this, binding system did the same thing like above to find out the scope to observe, which only has 1 scope and it is app instance. So it turns property `selectedThing` on app instance into a reactive property to observe for changes, which later helps binding system find the right scope in repeat.

Here is the only demo, if you want to examine this behavior easier https://codesandbox.io/s/nwm3w0wnk0

**Comment by rehanhilmy** [comment]
> @rehanhilmy Thanks for filing this, what you encountered is an expected behavior, not a bug. By default Aurelia binding system traverses the scope tree to find a matching property to observe. The scope tree in your cases comprises of repeat item and the app instance. It traverses from repeat item to app instance.
> 
>     * If the app instance does not have property `selectedThing`, the binding system fallbacks to repeat item scope, as it assumes that it's the intended scope. The binding system then starts observing the `selectedThing` property on **repeat item**, which will make it not displaying any changes when you click on any item, because the click handler assign `thing` to `selectedThing` on app instance.
> 
>     * If the app instance has property `selectedThing`, the binding system can find it and decides app is the intended scope. The binding system then starts observing the `selectedThing` property on **app instance**, which will make it start to behave the way you want.
> 
> 
> > Write ${selectedThing} somewhere else in app.html.
> 
> When you did this, binding system did the same thing like above to find out the scope to observe, which only has 1 scope and it is app instance. So it turns property `selectedThing` on app instance into a reactive property to observe for changes, which later helps binding system find the right scope in repeat.
> 
> Here is the only demo, if you want to examine this behavior easier https://codesandbox.io/s/nwm3w0wnk0

It works, thanks!

**Comment by Tim-Erwin** [comment]
@bigopon , really helpful answer. Can we find this in the docs somewhere?
