### ISSUE TITLE
Constructor not called first

### ISSUE THREAD

**Issue by justindra** [aurelia/templating#663]
**I'm submitting a bug report**

* **Library Version:**
1.10.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.14

* **Node Version:**
10.15.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
Webpack 3.3.0

* **Browser:**
all

* **Language:**
TypeScript 3.2.2

**Current behavior:**
When I load one of my components using the `aurelia-dialog` I noticed that the constructor is not being called first. Instead this is the order when i just add a `console.log` in each of the functions:

```
observableOneChanged
observableTwoChanged 
constructor
activate
```

**Expected/desired behavior:**

I expect the constructor to always be run first
```
constructor
observableOneChanged
observableTwoChanged 
activate
```

* **What is the motivation / use case for changing the behavior?**

`constructor` should always be run first. I am running some setups in the constructor and it is breaking apart when its not called before the changed functions.

**Comment by StrahilKazlachev** [comment]
Do provide more information. What are those *observableOneChanged*, *observableTwoChanged*? Where are they implemented? Which *constructor*? What do you mean you *load* components with `aurelia-dialog`?

**Comment by justindra** [comment]
@StrahilKazlachev sorry for the lack of description. Here is some more information.

So here is example of the component

```ts
import { observable } from 'aurelia-framework';

export class ExampleDialog {
  @observable() observableOne = '';
  @observable() observableTwo = '';
  
  constructor() {
    console.log('constructor');
  }

  activate() {
    console.log('activate');
  }

  observableOneChanged() {
    console.log('observableOneChanged');
  }

  observableTwoChanged() {
    console.log('observableTwoChanged');
  }
}
```

and to instantiate the component

```ts
import { inject } from 'aurelia-framework';
import { DialogService } from 'aurelia-dialog';
import { ExampleDialog } from 'path-to-example-dialog'

@inject(DialogService)
export class MainComponent {
  constructor(
    private dialogService: DialogService
  ) {}

  openDialog() {
    this.dialogService.open({
      viewModel: ExampleDialog
    });
  }
}
```

**Comment by StrahilKazlachev** [comment]
Ah, so the way I see it, it is combination of the compiled code and how `@observable` works.
`@oservable` is synchronous, meaning the moment you assign to the property the change handler will be called.
Since you are using TS your compiled constructor should look like this:
```js
function ExampleDialog() {
    this.observableOne = '';
    this.observableTwo = '';
    console.log('constructor');
}
```
So because how `@observable`, when `this.observableOne = '';` is hit, before continuing to the next line, the change handler will be called.
So it may look as the constructor is being executed after the change handlers, but in reality the change handlers are executing during the constructor invocation.
I suppose you can drop the inline property initialization(`@observable() observableOne = '';`) and just init them in the `constructor` when appropriate. The change handlers will still be called!

**Comment by justindra** [comment]
Ah gotcha! That makes more sense. Thanks for that!
